# ---------------------------------------------------
# Makefile  v19.04.28j   for  x86_64-apple-darwin18
# Serial No. 2019-0501-654321 Licensed under GNU GPL.
# Copyright (C) 2011 Douglas Goodall,  United States.
# ---------------------------------------------------
#  autogenerated by makemake.cpp 
# 
QUIET    = @
MACHTYPE = x86_64-apple-darwin18
PWD      = /Users/doug/src/framewk/04282019
OSTYPE   = darwin18
UID      = 501
USER     = doug
CC       = g++
CCFLAGS  = -w 

SOURCES  = editall.cpp a.cpp testenv.cpp f.cpp shex.cpp testxor.cpp d.cpp l8085.cpp mkbindef.cpp ascii.cpp makemake.cpp bin2com.cpp hello.cpp fdisk.cpp cvtall.cpp sb.cpp cvt.cpp dir.cpp sw.cpp asmall.cpp bin2hex.cpp testpfix.cpp testdefs.cpp lc.cpp assemble.cpp load.cpp document.cpp makevers.cpp dump.cpp m.cpp lz80.cpp mvall.cpp lhex.cpp 

INCLUDES = asdecz80.hpp globdata.hpp asdec65.hpp asdefs.hpp asdec68k.hpp asdecdir.hpp asymbols.hpp srcclass.hpp environ.hpp asmultip.hpp bcctrace.hpp asouthex.hpp portab.hpp asoutlst.hpp asomfgen.hpp inibind.hpp cpostfix.hpp dirclass.hpp asprint.hpp includes.hpp asoutwrn.hpp ascalc.hpp asdec20.hpp cbindefs.hpp strupr.hpp pcascii.hpp asdec85.hpp asresolv.hpp strlwr.hpp memory.hpp asparse.hpp defaults.hpp asparse2.hpp aseval.hpp dwgalloc.hpp asouterr.hpp asomfdef.hpp ashexout.hpp asdec80.hpp versbind.hpp 

BINARIES = editall a testenv f shex testxor d l8085 mkbindef ascii makemake bin2com hello fdisk cvtall sb cvt dir sw asmall bin2hex testpfix testdefs lc assemble load document makevers dump m lz80 mvall lhex 

INSTBINS = ~/bin/editall ~/bin/a ~/bin/testenv ~/bin/f ~/bin/shex ~/bin/testxor ~/bin/d ~/bin/l8085 ~/bin/mkbindef ~/bin/ascii ~/bin/makemake ~/bin/bin2com ~/bin/hello ~/bin/fdisk ~/bin/cvtall ~/bin/sb ~/bin/cvt ~/bin/dir ~/bin/sw ~/bin/asmall ~/bin/bin2hex ~/bin/testpfix ~/bin/testdefs ~/bin/lc ~/bin/assemble ~/bin/load ~/bin/document ~/bin/makevers ~/bin/dump ~/bin/m ~/bin/lz80 ~/bin/mvall ~/bin/lhex 

COMMON   = ascommon/pass2msg.hpp ascommon/radix.hpp ascommon/equ.hpp ascommon/segment.hpp ascommon/dotend.hpp ascommon/cpu.hpp ascommon/org.hpp ascommon/dstr.hpp ascommon/serializ.hpp ascommon/typeinc.hpp ascommon/symlist.hpp ascommon/dotbyte.hpp ascommon/pageleng.hpp ascommon/pagewide.hpp ascommon/orgminus.hpp ascommon/include.hpp ascommon/title.hpp ascommon/copr.hpp ascommon/equ32.hpp ascommon/dotdb.hpp ascommon/dstrz.hpp ascommon/calc.hpp ascommon/export.hpp ascommon/_disp.hpp ascommon/serial.hpp ascommon/rw.hpp ascommon/dotequ.hpp ascommon/copywrit.hpp ascommon/end.hpp ascommon/debug.hpp ascommon/equ8.hpp ascommon/public.hpp ascommon/dotorg.hpp ascommon/rb.hpp ascommon/dsa.hpp ascommon/db.hpp ascommon/listradx.hpp ascommon/byte.hpp ascommon/dstrb.hpp ascommon/dstr4.hpp ascommon/extrn.hpp ascommon/pass1msg.hpp ascommon/binary.hpp ascommon/proc.hpp ascommon/equ64.hpp ascommon/orgplus.hpp ascommon/equ16.hpp ascommon/namespac.hpp ascommon/page.hpp ascommon/log.hpp ascommon/dsal.hpp ascommon/dottitle.hpp ascommon/dsah.hpp ascommon/subttl.hpp ascommon/verbsity.hpp ascommon/cpm.hpp ascommon/message.hpp ascommon/typesrc.hpp ascommon/savesym.hpp ascommon/listincl.hpp 

I8085    = as8085/lda_85.hpp as8085/inx_85.hpp as8085/pop_85.hpp as8085/rar_85.hpp as8085/dd_85.hpp as8085/rz_85.hpp as8085/xri_85.hpp as8085/jnc_85.hpp as8085/dotdw_85.hpp as8085/adi_85.hpp as8085/ldax_85.hpp as8085/im_85.hpp as8085/cnz_85.hpp as8085/rlc_85.hpp as8085/cmp_85.hpp as8085/ana_85.hpp as8085/sbb_85.hpp as8085/jpe_85.hpp as8085/rpo_85.hpp as8085/nop_85.hpp as8085/adc_85.hpp as8085/jc_85.hpp as8085/rnc_85.hpp as8085/rp_85.hpp as8085/cc_85.hpp as8085/sub_85.hpp as8085/inr_85.hpp as8085/daa_85.hpp as8085/sbr_85.hpp as8085/rrc_85.hpp as8085/ral_85.hpp as8085/ani_85.hpp as8085/rpe_85.hpp as8085/sphl_85.hpp as8085/cm_85.hpp as8085/jpo_85.hpp as8085/hlt_85.hpp as8085/jm_85.hpp as8085/lxi_85.hpp as8085/xra_85.hpp as8085/aci_85.hpp as8085/add_85.hpp as8085/jnz_85.hpp as8085/in_85.hpp as8085/jmp_85.hpp as8085/jp_85.hpp as8085/ori_85.hpp as8085/xthl_85.hpp as8085/di_85.hpp as8085/rc_85.hpp as8085/ret_85.hpp as8085/dq_85.hpp as8085/push_85.hpp as8085/cpi_85.hpp as8085/cpe_85.hpp as8085/cp_85.hpp as8085/sui_85.hpp as8085/shld_85.hpp as8085/ei_85.hpp as8085/stax_85.hpp as8085/rm_85.hpp as8085/dad_85.hpp as8085/dcx_85.hpp as8085/cnc_85.hpp as8085/call_85.hpp as8085/cz_85.hpp as8085/cpo_85.hpp as8085/dw_85.hpp as8085/and_85.hpp as8085/sta_85.hpp as8085/rst_85.hpp as8085/cma_85.hpp as8085/jz_85.hpp as8085/mov_85.hpp as8085/xchg_85.hpp as8085/rnz_85.hpp as8085/ora_85.hpp as8085/sim_85.hpp as8085/rim_85.hpp as8085/cmc_85.hpp as8085/pchl_85.hpp as8085/lhld_85.hpp as8085/out_85.hpp as8085/mvi_85.hpp as8085/stc_85.hpp as8085/dcr_85.hpp as8085/sbi_85.hpp 

R6502    = as6502/bcc.hpp as6502/bvc.hpp as6502/bmi.hpp as6502/bne.hpp as6502/bvs.hpp as6502/bcs.hpp as6502/_bshort.hpp as6502/beq.hpp as6502/bpl.hpp as6502/nop.hpp as6502/op.hpp 

M68000   = as68000/unlk.hpp as68000/stop.hpp as68000/link.hpp as68000/extw.hpp as68000/illegal.hpp as68000/reset.hpp as68000/rts.hpp as68000/rte.hpp as68000/rtr.hpp as68000/dw.hpp as68000/dd.hpp as68000/dq.hpp as68000/extl.hpp as68000/nop.hpp as68000/trapv.hpp 

I8080    = as8080/filler.hpp 

Z80      = asz80/ldir.hpp asz80/indr.hpp asz80/outi.hpp asz80/rra.hpp asz80/cpir.hpp asz80/add.hpp asz80/otir.hpp asz80/rrd.hpp asz80/djnz.hpp asz80/inir.hpp asz80/odtr.hpp asz80/ld.hpp asz80/lddr.hpp asz80/cpdr.hpp asz80/cpd.hpp asz80/rst.hpp asz80/sub.hpp asz80/ex.hpp asz80/scfg.hpp asz80/dotword.hpp asz80/out.hpp asz80/exx.hpp asz80/ldi.hpp asz80/im.hpp asz80/rld.hpp asz80/retn.hpp asz80/in.hpp asz80/and.hpp asz80/dec.hpp asz80/rla.hpp asz80/ini.hpp asz80/jp.hpp asz80/jr.hpp asz80/reti.hpp asz80/ccf.hpp asz80/rrca.hpp asz80/halt.hpp asz80/neg.hpp asz80/ind.hpp asz80/dw.hpp asz80/dd.hpp asz80/call.hpp asz80/pop.hpp asz80/push.hpp asz80/ldd.hpp asz80/inc.hpp asz80/dq.hpp asz80/nop.hpp asz80/ret.hpp asz80/cpi.hpp asz80/or.hpp asz80/cp.hpp asz80/daa.hpp asz80/rlca.hpp asz80/outd.hpp asz80/scf.hpp asz80/cpl.hpp as1620/add.hpp as1620/nop.hpp 

I1620    = 

DEPENDS  = $(SOURCES) $(COMMON) $(I8085) $(I8080) $(M68000) $(R6502) $(Z80) $(I1620)

DECLS    = ascommon/decoincl.hpp as8080/decoincl.hpp as8085/decoincl.hpp as6502/decoincl.hpp asz80/decoincl.hpp as1620/decoincl.hpp as68000/decoincl.hpp

all:	$(BINARIES) GPATH 

version.hpp:	makevers
	$(QUIET)./makevers

GPATH:	$(DEPENDS)
	$(QUIET)gtags >gtags.log 2>gtags.log
	$(QUIET)htags >htags.log 2>htags.log

editall:	editall.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) editall.cpp -o editall

a:	a.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) a.cpp -o a

testenv:	testenv.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) testenv.cpp -o testenv

f:	f.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) f.cpp -o f

shex:	shex.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) shex.cpp -o shex

testxor:	testxor.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) testxor.cpp -o testxor

d:	d.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) d.cpp -o d

l8085:	l8085.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) l8085.cpp -o l8085

mkbindef:	mkbindef.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) mkbindef.cpp -o mkbindef

ascii:	ascii.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) ascii.cpp -o ascii

makemake:	makemake.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) makemake.cpp -o makemake

bin2com:	bin2com.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) bin2com.cpp -o bin2com

hello:	hello.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) hello.cpp -o hello

fdisk:	fdisk.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) fdisk.cpp -o fdisk

cvtall:	cvtall.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) cvtall.cpp -o cvtall

sb:	sb.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) sb.cpp -o sb

cvt:	cvt.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) cvt.cpp -o cvt

dir:	dir.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) dir.cpp -o dir

sw:	sw.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) sw.cpp -o sw

asmall:	asmall.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) asmall.cpp -o asmall
	$(QUIET)cp asmall astests

bin2hex:	bin2hex.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) bin2hex.cpp -o bin2hex

testpfix:	testpfix.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) testpfix.cpp -o testpfix

testdefs:	testdefs.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) testdefs.cpp -o testdefs

lc:	lc.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) lc.cpp -o lc

assemble:	assemble.cpp $(INCLUDES) version.hpp Makefile $(DEPENDS) $(DECLS)
	$(CC) $(CCFLAGS) assemble.cpp -o assemble
	$(QUIET)rm -f $(DECLS)

load:	load.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) load.cpp -o load

document:	document.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) document.cpp -o document

makevers:	makevers.cpp $(INCLUDES) Makefile 
	$(CC) $(CCFLAGS) makevers.cpp -o makevers

dump:	dump.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) dump.cpp -o dump

m:	m.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) m.cpp -o m

lz80:	lz80.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) lz80.cpp -o lz80

mvall:	mvall.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) mvall.cpp -o mvall

lhex:	lhex.cpp $(INCLUDES) version.hpp Makefile 
	$(CC) $(CCFLAGS) lhex.cpp -o lhex

as8085/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  as8085/Makefile
	$(QUIET)make -B -C as8085

as8080/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  as8080/Makefile
	$(QUIET)make -B -C as8080

as6502/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  as6502/Makefile
	$(QUIET)make -B -C as6502

asz80/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  asz80/Makefile
	$(QUIET)make -B -C asz80

as68000/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  as68000/Makefile
	$(QUIET)make -B -C as68000

as1620/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  as1620/Makefile
	$(QUIET)make -B -C as1620

ascommon/decoincl.hpp:	Makefile
	$(QUIET)cp makedeco.mk  ascommon/Makefile
	$(QUIET)make -B -C ascommon


clean:
	$(QUIET)rm -f editthem version.hpp *.mak *.lst *hex *.map *.log 
	$(QUIET)rm -f ascommon/editall ascommon/decoincl.hpp ascommon/makedeco ascommon/Makefile ascommon/makedeco.cpp ascommon/decoincl.sav ascommon/editall.ini ascommon/editthem as8085/editall   as8085/decoincl.hpp   as8085/makedeco   as8085/Makefile as8085/makedeco.cpp as8085/decoincl.sav as8085/editall.ini as8085/editthem asz80/editall    asz80/decoincl.hpp    asz80/makedeco    asz80/Makefile asz80/makedeco.cpp asz80/decoincl.sav asz80/editall.ini asz80/editthem as8080/editall   as8080/decoincl.hpp   as8080/makedeco   as8080/Makefile as8080/makedeco.cpp as8080/decoincl.sav as8080/editall.ini as8080/editthem as68000/editall  as68000/decoincl.hpp  as68000/makedeco  as68000/Makefile as68000/makedeco.cpp as68000/decoincl.sav as68000/editall.ini as68000/editthem as1620/editall  as1620/decoincl.hpp  as1620/makedeco  as1620/Makefile as1620/makedeco.cpp as1620/decoincl.sav as1620/editall.ini as1620/editthem as6502/editall   as6502/decoincl.hpp   as6502/makedeco   as6502/Makefile as6502/makedeco.cpp as6502/decoincl.sav as6502/editall.ini as6502/editthem doc/editall
	$(QUIET)rm -f astests/asmall astests/editall
	$(QUIET)rm -f editall a testenv f shex testxor d l8085 mkbindef ascii makemake bin2com hello fdisk cvtall sb cvt dir sw asmall bin2hex testpfix testdefs lc assemble load document makevers dump m lz80 mvall lhex 
	$(QUIET)rm -f -r *.sym astests/*.sym
	$(QUIET)rm -f astests/*.lst astests/*.log 
	$(QUIET)rm -f astests/*.hex astests/*.bin 
	$(QUIET)rm -f astests/*.obj 
	$(QUIET)rm -f -r G* HTML

installbins:
	cp $(BINARIES) ~/src/framewk/bin

uninstall:
	rm -f $(INSTBINS)

# eof - Makefile
