# ---------------------------------------------------
# Makefile     Ver 19.04.28j  x86_64-apple-darwin18
# Serial No. 2011-1042-654321    All Rights Reserved.
# Copyright (C) 2011 Douglas Goodall,  United States.
# ---------------------------------------------------
# Created by asmall.cpp  Sun Apr 28 09:16:57 PDT 2019


AS = ./assemble

HEXFILES = 

INCFILES = 

all:	$(HEXFILES)


clean:
	rm -f *.exp *.obj *.bin editthem *.lst *.log *.hex 
	rm -r -f  *.ini *.sym

# eof - Makefile
