// ---------------------------------------------------
// version.hpp  Ver 19.04.28j  x86_64-apple-darwin18
// Serial No. 2019-0501-654321                        
// Copyright(c)2019 Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Sun Apr 28 09:16:43 PDT 2019

#define RMJ 19
#define RMN 4
#define RUP 28
#define RTP 9
