// ---------------------------------------------------
// version.hpp  Ver 11.04.14j  x86_64-apple-darwin10.0
// Serial No. 2011-0501-654321                        
// Copyright(c)2011 Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Thu Apr 14 09:10:00 PDT 2011

#define RMJ 11
#define RMN 1
#define RUP 1
#define RTP 1
