// ---------------------------------------------------
// version.hpp  Ver 11.05.18t  x86_64-apple-darwin10.0
// Serial No. 2011-0501-654321                        
// Copyright(c)2011 Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Wed May 18 19:13:29 PDT 2011

#define RMJ 11
#define RMN 5
#define RUP 18
#define RTP 19
