; parttabl.asm generated by ./fdisk, do not edit

p$table:
P1:	dw 00001H,00000H,04000H,00000H	; C: of       8 MegaBytes
P2:	dw 04001H,00000H,08000H,00000H	; D: of       8 MegaBytes
P3:	dw 08001H,00000H,0C000H,00000H	; E: of       8 MegaBytes
P4:	dw 0C001H,00000H,0EF00H,00000H	; F: of       5 MegaBytes
