// ---------------------------------------------------
// version.hpp  Ver  0.1229148993.00a  i686-pc-cygwin
// Serial No. 20 A-1000-654321                        
// Copyright(c)20 A Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Mon, Jan 07, 2013  4:19:42 AM

#define RMJ 0
#define RMN 1229148993
#define RUP 0
#define RTP 0
