# ---------------------------------------------------
# mkfiles/test68k.mak  Ver 11.03.24c  
# Serial No. 2011-1042-654321    All Rights Reserved.
# Copyright (C) 2011 Douglas Goodall,  United States.
# ---------------------------------------------------
# mkfiles/test68k.mak autogenerated by asmall.cpp 
# Fri Mar 25 02:10:07 PDT 2011
# Copyright (c)2011 Douglas Goodall. Rights Reserved.

AS = ../assemble

INCFILES  = assemble.inc banner.inc cpm80.inc gplstuff.inc incl1.inc incl2.inc incl3.inc 

test68k.hex:	test68k.asm $(INCFILES) $(AS) 
	$(AS) test68k 

clean:
	rm -f *.bin  *.lst *.log *.hex

# eof - mkfiles/test68k.mak
