# ---------------------------------------------------
# Makefile     Ver 11.08.21c  x86_64-apple-darwin11
# Serial No. 2011-1042-654321    All Rights Reserved.
# Copyright (C) 2011 Douglas Goodall,  United States.
# ---------------------------------------------------
# Created by asmall.cpp  Sun Aug 21 02:26:51 PDT 2011


AS = ../assemble

HEXFILES = allz80.hex banner.hex dwgforth.hex hello85.hex salota.hex test.hex test1620.hex test6502.hex test8085.hex test85.hex test85dd.hex test85dq.hex test85dw.hex testaci.hex testdebg.hex testdirs.hex testdjnz.hex testdoll.hex testdtdb.hex testdw.hex testeval.hex testexp.hex testexpr.hex testhere.hex testincl.hex testinou.hex testmem.hex testmisc.hex testmov.hex testmvi.hex testns.hex testpage.hex testpass.hex testphex.hex testproc.hex testpubl.hex testradx.hex testrb.hex testsavs.hex testsbb.hex testsize.hex teststr.hex testsyml.hex testz8cp.hex testz8dw.hex testz8jp.hex testz8jr.hex testz8ld.hex testz8or.hex testzadd.hex testzcal.hex testzout.hex testzsub.hex 

INCFILES = assemble.inc banner.inc cpm80.inc gplstuff.inc incl1.inc incl2.inc incl3.inc printhex.inc 

all:	$(HEXFILES)


allz80.hex:	allz80.asm $(AS) Makefile $(INCFILES) 
	$(AS) allz80 

banner.hex:	banner.asm $(AS) Makefile $(INCFILES) 
	$(AS) banner 

dwgforth.hex:	dwgforth.asm $(AS) Makefile $(INCFILES) 
	$(AS) dwgforth 

hello85.hex:	hello85.asm $(AS) Makefile $(INCFILES) 
	$(AS) hello85 

salota.hex:	salota.asm $(AS) Makefile $(INCFILES) 
	$(AS) salota 

test.hex:	test.asm $(AS) Makefile $(INCFILES) 
	$(AS) test 

test1620.hex:	test1620.asm $(AS) Makefile $(INCFILES) 
	$(AS) test1620 

test6502.hex:	test6502.asm $(AS) Makefile $(INCFILES) 
	$(AS) test6502 

test8085.hex:	test8085.asm $(AS) Makefile $(INCFILES) 
	$(AS) test8085 

test85.hex:	test85.asm $(AS) Makefile $(INCFILES) 
	$(AS) test85 

test85dd.hex:	test85dd.asm $(AS) Makefile $(INCFILES) 
	$(AS) test85dd 

test85dq.hex:	test85dq.asm $(AS) Makefile $(INCFILES) 
	$(AS) test85dq 

test85dw.hex:	test85dw.asm $(AS) Makefile $(INCFILES) 
	$(AS) test85dw 

testaci.hex:	testaci.asm $(AS) Makefile $(INCFILES) 
	$(AS) testaci 

testdebg.hex:	testdebg.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdebg 

testdirs.hex:	testdirs.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdirs 

testdjnz.hex:	testdjnz.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdjnz 

testdoll.hex:	testdoll.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdoll 

testdtdb.hex:	testdtdb.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdtdb 

testdw.hex:	testdw.asm $(AS) Makefile $(INCFILES) 
	$(AS) testdw 

testeval.hex:	testeval.asm $(AS) Makefile $(INCFILES) 
	$(AS) testeval 

testexp.hex:	testexp.asm $(AS) Makefile $(INCFILES) 
	$(AS) testexp 

testexpr.hex:	testexpr.asm $(AS) Makefile $(INCFILES) 
	$(AS) testexpr 

testhere.hex:	testhere.asm $(AS) Makefile $(INCFILES) 
	$(AS) testhere 

testincl.hex:	testincl.asm $(AS) Makefile $(INCFILES) 
	$(AS) testincl 

testinou.hex:	testinou.asm $(AS) Makefile $(INCFILES) 
	$(AS) testinou 

testmem.hex:	testmem.asm $(AS) Makefile $(INCFILES) 
	$(AS) testmem 

testmisc.hex:	testmisc.asm $(AS) Makefile $(INCFILES) 
	$(AS) testmisc 

testmov.hex:	testmov.asm $(AS) Makefile $(INCFILES) 
	$(AS) testmov 

testmvi.hex:	testmvi.asm $(AS) Makefile $(INCFILES) 
	$(AS) testmvi 

testns.hex:	testns.asm $(AS) Makefile $(INCFILES) 
	$(AS) testns 

testpage.hex:	testpage.asm $(AS) Makefile $(INCFILES) 
	$(AS) testpage 

testpass.hex:	testpass.asm $(AS) Makefile $(INCFILES) 
	$(AS) testpass 

testphex.hex:	testphex.asm $(AS) Makefile $(INCFILES) 
	$(AS) testphex 

testproc.hex:	testproc.asm $(AS) Makefile $(INCFILES) 
	$(AS) testproc 

testpubl.hex:	testpubl.asm $(AS) Makefile $(INCFILES) 
	$(AS) testpubl 

testradx.hex:	testradx.asm $(AS) Makefile $(INCFILES) 
	$(AS) testradx 

testrb.hex:	testrb.asm $(AS) Makefile $(INCFILES) 
	$(AS) testrb 

testsavs.hex:	testsavs.asm $(AS) Makefile $(INCFILES) 
	$(AS) testsavs 

testsbb.hex:	testsbb.asm $(AS) Makefile $(INCFILES) 
	$(AS) testsbb 

testsize.hex:	testsize.asm $(AS) Makefile $(INCFILES) 
	$(AS) testsize 

teststr.hex:	teststr.asm $(AS) Makefile $(INCFILES) 
	$(AS) teststr 

testsyml.hex:	testsyml.asm $(AS) Makefile $(INCFILES) 
	$(AS) testsyml 

testz8cp.hex:	testz8cp.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8cp 

testz8dw.hex:	testz8dw.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8dw 

testz8jp.hex:	testz8jp.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8jp 

testz8jr.hex:	testz8jr.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8jr 

testz8ld.hex:	testz8ld.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8ld 

testz8or.hex:	testz8or.asm $(AS) Makefile $(INCFILES) 
	$(AS) testz8or 

testzadd.hex:	testzadd.asm $(AS) Makefile $(INCFILES) 
	$(AS) testzadd 

testzcal.hex:	testzcal.asm $(AS) Makefile $(INCFILES) 
	$(AS) testzcal 

testzout.hex:	testzout.asm $(AS) Makefile $(INCFILES) 
	$(AS) testzout 

testzsub.hex:	testzsub.asm $(AS) Makefile $(INCFILES) 
	$(AS) testzsub 

clean:
	rm -f *.exp *.obj *.bin editthem *.lst *.log *.hex 
	rm -r -f allz80 banner dwgforth hello85 salota test test1620 test6502 test8085 test85 test85dd test85dq test85dw testaci testdebg testdirs testdjnz testdoll testdtdb testdw testeval testexp testexpr testhere testincl testinou testmem testmisc testmov testmvi testns testpage testpass testphex testproc testpubl testradx testrb testsavs testsbb testsize teststr testsyml testz8cp testz8dw testz8jp testz8jr testz8ld testz8or testzadd testzcal testzout testzsub  *.ini *.sym

# eof - Makefile
