; parttabl.asm generated by ./fdisk, do not edit

p$table:
P1:	dw 00001H,00000H,00000H,00000H	; C: of       0 MegaBytes
P2:	dw 00001H,00000H,04000H,00000H	; D: of       8 MegaBytes
P3:	dw 04001H,00000H,04000H,00000H	; E: of       0 MegaBytes
P4:	dw 04001H,00000H,08000H,00000H	; F: of       8 MegaBytes
