; parttabl.asm generated by ./fdisk, do not edit

p$table:
P1:	dw 0001H,0000H,4000H,0000H	; C: of       8 MegaBytes
P2:	dw 4001H,0000H,8000H,0000H	; D: of       8 MegaBytes
P3:	dw 8001H,0000H,C000H,0000H	; E: of       8 MegaBytes
P4:	dw C001H,0000H,EF00H,0000H	; F: of       5 MegaBytes
