// ---------------------------------------------------
// version.hpp  Ver 11.08.21c  x86_64-apple-darwin11
// Serial No. 2011-0501-654321                        
// Copyright(c)2011 Douglas W. Goodall, United States.
// ---------------------------------------------------
// machine generated by makevers.cpp
//    Sun Aug 21 02:26:26 PDT 2011

#define RMJ 11
#define RMN 8
#define RUP 21
#define RTP 2
